# =========================================
# AI Code Context Generator Configuration
# =========================================

# Primary source directory containing the main codebase.
# Update this if your main code is not in 'src/'.
source_directory: src

# List of directories to exclude from the directory tree and file inclusions.
# These directories and their contents will be omitted from the generated context.
# Customize this list based on your project's structure.
exclude_dirs:
  - node_modules          # Node.js dependencies
  - venv                  # Python virtual environment
  - __pycache__           # Python bytecode cache
  - build                 # Build output directories
  - dist                  # Distribution packages
  - .git                  # Git repository metadata
  - .github               # GitHub workflows and configurations
  - .vscode               # Visual Studio Code settings
  - logs                  # Log files
  - tmp                   # Temporary files and directories

# List of important files to include in the context.
# Paths should be relative to the 'source_directory' specified above.
# These files are crucial for understanding the project's functionality.
# Modify this list to include files relevant to your project.
important_files:
  - main.py                         # Entry point of the application
  - app.py                          # Application configuration
  - config/settings.py              # Configuration settings
  - utils/helpers.py                # Utility helper functions
  - models/user.py                  # User model definitions
  - controllers/auth_controller.py  # Authentication controller
  - services/email_service.py       # Email service integration
  - routes/api_routes.py            # API route definitions
  - database/db_connection.py       # Database connection setup
  - tests/test_main.py              # Main application tests

# =========================================
# Instructions for Customization
# =========================================

# 1. **source_directory**:
#    - Set this to the primary directory containing your source code.
#    - Example:
#      - For a project with main code in 'app/', set `source_directory: app`

# 2. **exclude_dirs**:
#    - Review the list and remove any directories that are essential for your project context.
#    - Add any additional directories that you want to exclude by appending them to the list.
#    - Example:
#      - If your project uses a `docs/` directory for documentation, you might choose to exclude it:
#        - docs

# 3. **important_files**:
#    - Identify the key files in your project that define its core functionality.
#    - Ensure the paths are relative to your `source_directory`.
#    - Add or remove files as necessary to reflect your project's structure.
#    - Example:
#      - For a JavaScript project, you might include:
#        - index.js
#        - src/app.js
#        - src/routes/index.js
#        - src/controllers/userController.js

# =========================================
# Additional Configuration (Optional)
# =========================================

# Uncomment and customize the sections below if your project requires more advanced configurations.

# # List of file types to include based on extensions.
# # Useful if you want to include all files of certain types without specifying each one.
# file_type_inclusions:
#   - .js
#   - .ts
#   - .java
#   - .rb
#   - .go

# # List of file types to exclude based on extensions.
# # This can help in omitting large binary files or irrelevant file types.
# file_type_exclusions:
#   - .log
#   - .tmp
#   - .png
#   - .jpg
#   - .gif

# # Custom sections to include additional information.
# # You can define more sections by adding corresponding static files.
custom_sections:
  - file: changelog.txt
    section_title: "Changelog"
  - file: LICENSE.txt
    section_title: "License"
